### ISSUE TITLE
Ctrl+Mousewheel issue

### ISSUE THREAD

**Issue by CariTheKitty** [gantt42/Creature-History-Client#120]
Ctrl+mousewheel does not zoom in and out, but zooms the input of the mouse, misaligning from the pointer. closing a file and reopening it then shows the updated "Zoom". at differing zooms the ctrl clicking/dragging of room corners becomes inconsistent.

**Comment by JGantts** [comment]
239ceec77f5acc09b21c3fab34045d2c5a1044d4
